# Merge-Request Pipeline
workflow:
  rules:
    - if: $CI_RUNNER_SHORT_TOKEN != "qUVpQxcL"
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_PROJECT_URL != "https://gitlab.com/nitk-nest/nest"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


default:
  # https://github.com/manoj-sys/SecOne/blob/master/Dockerfile
  image: shaman53/trydocky:latest

stages:
  - build
  - test
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


build nest:
  stage: build
  script:
    - pip install .

run pylint:
  stage: test
  script:
    - pylint --version
    - pylint nest

run unit tests:
  stage: test
  script:
    # Install NeST
    - pip install .

    # Run unit tests
    - coverage --version
    - coverage run --parallel-mode --source nest -m unittest -v
    - apt install -y frr
    - coverage run --parallel-mode --source nest -m unittest nest/tests/test_routing_frr.py -v
    - coverage combine
    - coverage report
    - coverage xml

  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - test-experiment*/

test docs:
  stage: test
  script:
    - make -C docs html
  rules:
    - changes:
        - docs/*

upload to PyPI:
  stage: release
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/* --verbose
  only:
    - tags
