# Merge-Request Pipeline
workflow:
  rules:
    # - if: $CI_RUNNER_SHORT_TOKEN != "qUVpQxcL"
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_PROJECT_URL != "https://gitlab.com/nitk-nest/nest"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


default:
  image: python:latest

stages:
  - build
  - test
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  # Create virtual env
  - python -V
  - python -m venv venv
  - source venv/bin/activate

build nest:
  stage: build
  script:
    - pip install .

run style check:
  stage: test
  script:
    - pip install pre-commit
    - pre-commit --version
    - pre-commit run --all-files

    - pip install gitlint
    - gitlint --version
    - git fetch
    - gitlint --commits origin/master..HEAD

run unit tests:
  stage: test
  script:
    # Install NeST
    - pip install .

    # Install dependencies Netperf and Quagga
    # Install netperf
    - git clone https://github.com/HewlettPackard/netperf.git
    - cd netperf
    - git checkout netperf-2.7.0
    - sh ./configure
    - make install
    - netperf -V
    - cd ..

    # Install quagga
    - apt-get update
    - apt-get -y install quagga
    - zebra -v
    - mkdir -p  /run/quagga
    - chown quagga:quagga /run/quagga
    - rm -f /etc/quagga/daemons
    - |
      echo "zebra=yes
      ospfd=yes
      ripd=yes" >> /etc/quagga/daemons

    # FRR can't be installed alongside quagga

    # Run unit tests
    - pip install coverage
    - coverage --version
    - coverage run --parallel-mode --source nest -m unittest -v
    - apt install -y frr
    - coverage run --parallel-mode --source nest -m unittest nest/tests/test_routing_frr.py -v
    - coverage combine
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - test-experiment*/

test docs:
  stage: test
  script:
    - pip install -r docs/doc_requirements.txt
    - make -C docs html
  rules:
    - changes:
        - docs/*

upload to PyPI:
  stage: release
  script:
    - pip install -U twine setuptools wheel
    - python setup.py sdist bdist_wheel
    - twine upload dist/* --verbose
  only:
    - tags
